<?php

namespace App\Controllers\Admin;

use Core\Controller;


class Users extends Controller
{

    protected function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }

    protected function after()
    {
        parent::after(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        echo 'User ADMIN - index';
    }
}